baseURL = "/"
defaultContentLanguage = "zh"
languageCode = "zh"
themesDir = "themes"
title = "PeterPans 真相"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""
  contact_us_content = "#Hi!"

  custom_css = ["css/styles.css"]

  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/logo.svg"
    alt = "Serif - A Hugo Business Theme"

  [params.homepage_meta_tags]
    meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_og_title = "Hugo Serif Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[languages.zh]
  languageCode = "zh"
[languages.en]
  languageCode = "en"
  contentDir = "content-en"
  title = "En Truth"

[menu]
  # Main Menu
  [[menu.main]]
    name = "主页"
    url = "/"
      weight = 1

  [[menu.main]]
    name = "事情起因"
    url = "/introduction/"
      weight = 2

  [[menu.main]]
    identifier="关于彼岸国际"
    name = "关于彼岸国际"
    url = "/aboutpeterpans/"
      weight = 3

      [[menu.main]]
      name="关于哈佛哥大梦幻顾问团队"
      parent="关于彼岸国际"
      url="/aboutpeterpans/关于哈佛哥大梦幻顾问团队"
      weight=1

      [[menu.main]]
      name="关于千人导师团队"
      parent="关于彼岸国际"
      url="/aboutpeterpans/关于千人导师团队"
      weight=2

      [[menu.main]]
      name="关于往届offer"
      parent="关于彼岸国际"
      url="/aboutpeterpans/关于往届offer"
      weight=3

  [[menu.main]]
    identifier="关于创始人高博"
    name = "关于创始人高博"
    url = "/aboutdrGao/"
    weight = 4

      [[menu.main]]
        name="关于高博与哈佛"
        parent="关于创始人高博"
        url="/aboutdrGao/关于高博与哈佛/"
        weight = 1

      [[menu.main]]
        name="关于哈佛-哥大联合培养博士"
        parent="关于创始人高博"
        url="/aboutdrGao/关于联合培养博士/"
        weight = 2

      [[menu.main]]
        name="关于发表的论文"
        parent="关于创始人高博"
        url="/aboutdrGao/关于发表的论文/"
        weight = 3

      [[menu.main]]
        name="关于欧洲原子能机构研究员"
        parent="关于创始人高博"
        url="/aboutdrGao/关于欧洲原子能机构研究员/"
        weight = 4

      [[menu.main]]
        name="关于哥大招生官"
        parent="关于创始人高博"
        url="/aboutdrGao/关于哥大招生官/"
        weight = 5

    [[menu.main]]
      name = "关于我们"
      url = "/contact/"
        weight = 5

  # Footer Menu
